options:
  logging: CLOUD_LOGGING_ONLY

steps:
- name: gcr.io/cloud-builders/docker
  args:
    - build
    - -t
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
    - .

- name: gcr.io/cloud-builders/docker
  args:
    - push
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA

- name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_SERVICE}
    - --region=${_REGION}
    - --platform=managed
    - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
    - --service-account=${_RUNTIME_SA}
    - --allow-unauthenticated

substitutions:
  _REGION: asia-east2
  _REPO: backend
  _SERVICE: hku-aia-backend
  _RUNTIME_SA: 841899024016-compute@developer.gserviceaccount.com
